services:
  builder:
    container_name: wasm-builder
    platform: "linux/amd64"
    build:
      context: ./wasm
      dockerfile: Dockerfile
    working_dir: /go/src/app/wasm
    volumes:
      - ./:/go/src/app
    command:
      - tail
      - -f
      - /dev/null
