# https://taskfile.dev

version: "3"

tasks:
  build:
    cmds:
      - GOOS=js GOARCH=wasm go build -o ../public/main.wasm
      - cp /usr/local/go/misc/wasm/wasm_exec.js ../public/
    silent: true
